name: CI

on: [push]

jobs:
  unit-tests:
    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: "7.4"
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_version: "7.4"
          version: "7.*"