name: PHP

on: [push]

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Install dependencies
        run: |
          composer install
      - name: Run tests
        run: |
          vendor/bin/phpunit