name: CI

on: [push]

jobs:
  static-code-analysis:
    name: Static Code Analysis

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install dependencies
        run: |
          composer install
      - name: Run code analyse
        run: |
          vendor/bin/phpstan analyse src tests

  code-style:
    name: Code Style

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install dependencies
        run: |
          composer install
      - name: Run code style check
        run: |
          vendor/bin/ecs

  tests:
    name: Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install dependencies
        run: |
          composer install
      - name: Run tests
        run: |
          vendor/bin/phpunit